#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <cstdint>
#include <algorithm>
#include <array>
#include <exception>
#include <memory>
#include <stack>
#include <cassert>